const $=s=>document.querySelector(s),SIZE=15;
const puzzles=[['HARBOR','BRICK'],['MAPLE','TIDE'],['BEACON','STONE'],['COBALT','RIVER'],['BREEZE','CLOCK'],['MARKET','WHALE'],['CANDLE','SHORE'],['COPPER','TRAIL'],['GARDEN','LIGHT'],['NORTH','PIANO']];
const state={board:[],words:[],score:0,selected:null,direction:'horizontal',mode:'daily',puzzleIndex:0,sound:true,selectedDailyDate:new Date()};
const difficulties=['Easy','Easy +','Relaxed','Medium','Tricky','Hard','Expert'];
const localDateKey=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
const parseLocalDate=key=>{const [year,month,day]=key.split('-').map(Number);return new Date(year,month-1,day)};
const weekStartFor=d=>{const x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-x.getDay());return x};
const dailyIndexFor=d=>{const start=weekStartFor(d),week=Math.floor(start.getTime()/604800000);return((week*7+d.getDay())%puzzles.length+puzzles.length)%puzzles.length};
const puzzleNumber=d=>Math.floor((new Date(d)-new Date(2026,0,1))/86400000)+1;
const blankBoard=()=>Array.from({length:SIZE},()=>Array(SIZE).fill(null));
const coordsFor=(word,row,col,dir)=>[...word].map((letter,i)=>({row:row+(dir==='vertical'?i:0),col:col+(dir==='horizontal'?i:0),letter}));
function placeRaw(word,row,col,dir,type,id){coordsFor(word,row,col,dir).forEach(p=>{if(!state.board[p.row][p.col])state.board[p.row][p.col]={letter:p.letter,types:new Set(),wordIds:new Set()};state.board[p.row][p.col].types.add(type);state.board[p.row][p.col].wordIds.add(id)});state.words.push({id,word,row,col,dir,type,cost:type==='player'?10+word.length:0})}
function renderWeekCalendar(){const calendar=$('#weekCalendar');calendar.hidden=state.mode!=='daily';if(state.mode!=='daily')return;const start=weekStartFor(state.selectedDailyDate),todayKey=localDateKey(new Date());$('#weekDays').innerHTML=Array.from({length:7},(_,day)=>{const date=new Date(start);date.setDate(start.getDate()+day);const key=localDateKey(date),selected=key===localDateKey(state.selectedDailyDate);return`<button class="day-puzzle ${selected?'selected':''} ${key===todayKey?'today':''}" data-date="${key}" aria-pressed="${selected}" aria-label="${date.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}, ${difficulties[day]} puzzle"><span>${date.toLocaleDateString('en-US',{weekday:'short'})}</span><b>${date.getDate()}</b><small>${difficulties[day]}</small></button>`}).join('')}
function setupGame(forceIndex){state.board=blankBoard();state.words=[];state.score=0;state.selected=null;const day=state.selectedDailyDate.getDay();state.puzzleIndex=forceIndex??(state.mode==='daily'?dailyIndexFor(state.selectedDailyDate):Math.floor(Math.random()*puzzles.length));const [first,second]=puzzles[state.puzzleIndex],startRow=state.mode==='daily'?Math.max(1,4-Math.floor(day/2)):2,endRow=state.mode==='daily'?8+Math.ceil(day*4/3):11;placeRaw(first,startRow,1,'horizontal','start','start-a');placeRaw(second,Math.min(13,endRow),13-second.length,'horizontal','start','start-b');$('#startWordLabel').textContent=first;$('#endWordLabel').textContent=second;$('#score').textContent='0';$('#turnNumber').textContent='01';$('#wordInput').value='';$('#liveCost').textContent='+10';$('#message').textContent='';$('#undoBtn').disabled=true;$('#replayBtn').hidden=state.mode==='daily';$('#modeKicker').textContent=state.mode==='daily'?`${state.selectedDailyDate.toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'})} · ${difficulties[day]} · No. ${puzzleNumber(state.selectedDailyDate)}`:'Infinite play · Fresh board';renderWeekCalendar();updateBest();renderBoard();updateSelectionNote()}
function renderBoard(preview=[]){const pm=new Map(preview.map(p=>[`${p.row},${p.col}`,p]));let html='';for(let row=0;row<SIZE;row++)for(let col=0;col<SIZE;col++){const cell=state.board[row][col],p=pm.get(`${row},${col}`),types=cell?[...cell.types]:[],cross=cell&&cell.wordIds.size>1,classes=['cell',cell?'occupied':'',types.includes('start')?'start-word':'',types.includes('player')?'player-word':'',cross?'crossing':'',state.selected?.row===row&&state.selected?.col===col?'selected':'',p?p.valid?'preview':'preview-invalid':''].filter(Boolean).join(' ');html+=`<button class="${classes}" role="gridcell" data-row="${row}" data-col="${col}" aria-label="Row ${row+1}, column ${col+1}${cell?`, letter ${cell.letter}`:''}">${cell?.letter||p?.letter||'·'}</button>`}$('#board').innerHTML=html}
function updateSelectionNote(){const n=$('#selectionNote');n.innerHTML=state.selected?`<b>Starts at row ${state.selected.row+1}, column ${state.selected.col+1}.</b><span>Placing ${state.direction==='horizontal'?'across →':'down ↓'}</span>`:'<b>No starting square selected.</b><span>Click any square on the grid.</span>'}
function candidate(){const word=$('#wordInput').value.toUpperCase().replace(/[^A-Z]/g,'');if(!state.selected||!word)return{word,cells:[],valid:false};const cells=coordsFor(word,state.selected.row,state.selected.col,state.direction),inside=cells.every(p=>p.row>=0&&p.row<SIZE&&p.col>=0&&p.col<SIZE),compatible=inside&&cells.every(p=>!state.board[p.row][p.col]||state.board[p.row][p.col].letter===p.letter);return{word,cells:cells.map(p=>({...p,valid:inside&&compatible})),valid:inside&&compatible}}
function preview(){const c=candidate();renderBoard(c.cells);$('#liveCost').textContent=`+${10+c.word.length}`}
function wordGraph(){const graph=new Map(state.words.map(w=>[w.id,new Set()]));state.board.flat().filter(Boolean).forEach(cell=>{const ids=[...cell.wordIds];for(const a of ids)for(const b of ids)if(a!==b)graph.get(a).add(b)});return graph}
function reachableFrom(id){const graph=wordGraph(),seen=new Set([id]),queue=[id];while(queue.length)for(const next of graph.get(queue.shift())||[])if(!seen.has(next)){seen.add(next);queue.push(next)}return seen}
function isWinningBridge(crosses){if(crosses.length!==2)return false;const fromStart=reachableFrom('start-a'),fromFinish=reachableFrom('start-b');return crosses.some(p=>[...state.board[p.row][p.col].wordIds].some(id=>fromStart.has(id)))&&crosses.some(p=>[...state.board[p.row][p.col].wordIds].some(id=>fromFinish.has(id)))}
function validate(c){if(c.word.length<2)return'Use at least two letters.';if(!state.selected)return'Choose a starting square on the grid.';if(!c.valid)return'That word runs off the board or conflicts with a letter.';const crosses=c.cells.filter(p=>state.board[p.row][p.col]);if(crosses.length!==1&&!isWinningBridge(crosses))return crosses.length===0?'Your word must cross one existing word.':'Cross one word at a time—except your final bridge, which may cross your chain and the finish word.';if(c.cells.every(p=>state.board[p.row][p.col]))return'Add a new word, not one already on the board.';if(state.words.some(w=>w.word===c.word))return'That word is already on this board.';return''}
function connected(){return reachableFrom('start-a').has('start-b')}
function tone(freq=420){if(!state.sound)return;try{const ctx=new(AudioContext||webkitAudioContext),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.05,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.12);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.13)}catch{}}
function placeWord(){const c=candidate(),error=validate(c),m=$('#message');if(error){m.textContent=error;m.className='message';tone(180);return}placeRaw(c.word,state.selected.row,state.selected.col,state.direction,'player',`word-${Date.now()}`);state.score+=10+c.word.length;$('#score').textContent=state.score;$('#turnNumber').textContent=String(state.words.filter(w=>w.type==='player').length+1).padStart(2,'0');state.selected=null;$('#wordInput').value='';$('#liveCost').textContent='+10';$('#undoBtn').disabled=false;m.textContent=`${c.word} added for ${10+c.word.length} points.`;m.className='message success';tone(520);renderBoard();updateSelectionNote();if(connected())setTimeout(showResult,400)}
function undo(){const players=state.words.filter(w=>w.type==='player');if(!players.length)return;const last=players.at(-1);state.words=state.words.filter(w=>w.id!==last.id);state.score-=last.cost;state.board=blankBoard();const copy=[...state.words];state.words=[];copy.forEach(w=>placeRaw(w.word,w.row,w.col,w.dir,w.type,w.id));$('#score').textContent=state.score;$('#turnNumber').textContent=String(state.words.filter(w=>w.type==='player').length+1).padStart(2,'0');$('#undoBtn').disabled=!state.words.some(w=>w.type==='player');$('#message').textContent=`Removed ${last.word}.`;renderBoard()}
const bestKey=()=>state.mode==='daily'?`wordlinks-daily-${localDateKey(state.selectedDailyDate)}`:'wordlinks-infinite-best';
function updateBest(){const best=localStorage.getItem(bestKey());$('#bestScore').textContent=best||'—'}
function showResult(){const old=Number(localStorage.getItem(bestKey()))||Infinity,isBest=state.score<old;if(isBest)localStorage.setItem(bestKey(),state.score);$('#finalScore').textContent=state.score;$('#resultBest').textContent=isBest?'A new personal best':`Personal best: ${old}`;const count=state.words.filter(w=>w.type==='player').length;$('#resultSummary').textContent=`You connected ${puzzles[state.puzzleIndex][0]} to ${puzzles[state.puzzleIndex][1]} using ${count} ${count===1?'word':'words'}.`;$('#beatScoreBtn').hidden=state.mode==='daily';$('#nextPuzzleBtn').textContent=state.mode==='daily'?'Choose another day':'Play another word';$('#resultDialog').showModal();tone(700)}
function showGame(){$('#welcomeView').hidden=true;$('#gameView').hidden=false;setupGame();scrollTo({top:0,behavior:'smooth'})}
$('#todayLabel').textContent=new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'});$('#playBtn').onclick=showGame;$('#skipBtn').onclick=showGame;$('#brandLink').onclick=e=>{e.preventDefault();$('#gameView').hidden=true;$('#welcomeView').hidden=false};
$('#board').onclick=e=>{const c=e.target.closest('.cell');if(!c)return;state.selected={row:+c.dataset.row,col:+c.dataset.col};updateSelectionNote();preview();$('#wordInput').focus()};
document.querySelectorAll('.direction').forEach(b=>b.onclick=()=>{state.direction=b.dataset.direction;document.querySelectorAll('.direction').forEach(x=>x.classList.toggle('active',x===b));updateSelectionNote();preview()});
$('#wordInput').oninput=e=>{e.target.value=e.target.value.toUpperCase().replace(/[^A-Z]/g,'');preview()};$('#wordInput').onkeydown=e=>{if(e.key==='Enter')placeWord()};$('#placeBtn').onclick=placeWord;$('#undoBtn').onclick=undo;$('#replayBtn').onclick=()=>setupGame();
$('#weekDays').onclick=e=>{const button=e.target.closest('[data-date]');if(!button)return;state.selectedDailyDate=parseLocalDate(button.dataset.date);setupGame()};
document.querySelectorAll('.mode-tab').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;if(state.mode==='daily')state.selectedDailyDate=new Date();document.querySelectorAll('.mode-tab').forEach(x=>x.classList.toggle('active',x===b));if($('#gameView').hidden)showGame();else setupGame()});
$('#soundBtn').onclick=()=>{state.sound=!state.sound;$('#soundBtn').setAttribute('aria-pressed',state.sound);$('#soundBtn').setAttribute('aria-label',`Turn sound ${state.sound?'off':'on'}`)};$('#beatScoreBtn').onclick=()=>{$('#resultDialog').close();setupGame(state.puzzleIndex)};$('#nextPuzzleBtn').onclick=()=>{$('#resultDialog').close();if(state.mode==='daily'){$('#weekCalendar').scrollIntoView({behavior:'smooth',block:'center'});return}setupGame()};
const steps=[
['Meet your two starting words.','The two yellow words are the beginning and finish. Your goal is to create one unbroken chain between them.','<span class="hit">S</span><span>T</span><span>A</span><span>R</span><span>T</span>'],
['Pick a starting square.','Click the square where the first letter of your new word will sit. You may begin on an empty square or an existing matching letter.','<span>1</span><span>2</span><span class="hit">3</span><span>4</span><span>5</span>'],
['Choose across or down.','Use Across or Down before typing. The faint preview on the board shows exactly where every letter will land.','<span>A</span><span>C</span><span>R</span><span>O</span><span>S</span><span>S</span>'],
['Cross one matching letter.','Each added word normally crosses exactly one word already on the board. The shared square must contain the same letter in both words.','<span>B</span><span>R</span><span class="hit">I</span><span>D</span><span>G</span><span>E</span>'],
['Make the final bridge.','To finish, your last word may cross twice: once with your growing chain and once with the yellow finish word. When both sides touch, the puzzle ends.','<span class="hit">L</span><span>I</span><span>N</span><span class="hit">K</span>'],
['Keep the score low.','Every placed word costs 10 points plus 1 point per letter. Short words and fewer moves make a better score.','<span>L</span><span>I</span><span>N</span><span>K</span><b class="demo-plus">= 14</b>'],
['Choose your daily challenge.','The weekly calendar gives every day a different puzzle. Sunday is easiest and the challenge grows each day until Saturday. Replay is available in Infinite Play.','<span>Sun</span><span>Wed</span><span class="hit">Sat</span>'],
['Use your game tools.','Undo removes your latest word. Maximize fills your screen, and Infinite Play gives you fresh puzzles with a Replay option.','<span>↶</span><span>↻</span><span class="hit">⛶</span>']
];let step=0;
function renderTutorial(){const s=steps[step];const progress=$('.tutorial-progress');progress.innerHTML=steps.map(()=>'<i></i>').join('');progress.querySelectorAll('i').forEach((x,n)=>x.classList.toggle('active',n<=step));$('#tutorialContent').innerHTML=`<div class="tutorial-card"><div class="step-label">Step ${step+1} of ${steps.length}</div><h3>${s[0]}</h3><p>${s[1]}</p><div class="tutorial-demo"><div class="demo-word">${s[2]}</div></div></div>`;$('#tutorialBack').disabled=!step;$('#tutorialNext').innerHTML=step===steps.length-1?'Start playing <span>→</span>':'Next <span>→</span>'}
function tutorial(){step=0;renderTutorial();$('#tutorialDialog').showModal()}$('#tutorialBtn').onclick=tutorial;$('#howToBtn').onclick=tutorial;$('#closeTutorial').onclick=()=>$('#tutorialDialog').close();$('#tutorialBack').onclick=()=>{step--;renderTutorial()};$('#tutorialNext').onclick=()=>{if(step<steps.length-1){step++;renderTutorial()}else{$('#tutorialDialog').close();showGame()}};
function syncMaximize(){const active=document.fullscreenElement===$('#gameView');$('#maximizeBtn').innerHTML=active?'✕ <span>Exit full screen</span>':'⛶ <span>Maximize</span>';$('#gameView').classList.toggle('is-maximized',active)}
$('#maximizeBtn').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#gameView').requestFullscreen()}catch{$('#gameView').classList.toggle('window-maximized');$('#maximizeBtn').innerHTML=$('#gameView').classList.contains('window-maximized')?'✕ <span>Exit full screen</span>':'⛶ <span>Maximize</span>'}};document.addEventListener('fullscreenchange',syncMaximize);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#gameView').classList.contains('window-maximized')){$('#gameView').classList.remove('window-maximized');syncMaximize()}});
setupGame(dailyIndexFor(state.selectedDailyDate));
